version: '3.8'

services:
  mysql:
    build:
      context: ./dbs/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  mssql:
    build:
      context: ./dbs/mssql 
      dockerfile: Dockerfile
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourStrong_Password123
      MSSQL_PID: Developer
    ports:
      - "1433:1433"

  postgres:
    build:
      context: ./dbs/postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  mongodb:
    build:
      context: ./dbs/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
